"""Template for a user-defined receiver."""

from __future__ import annotations

from hardware_in_loop import CaptureResult, HilContext, RxResult


def process(capture: CaptureResult, context: HilContext, params: dict) -> RxResult:
    """Process captured I/Q samples.

    Inputs:
        capture.samples: complex-baseband I/Q from the analyzer or dry-run loopback.
        capture.sample_rate_hz: sample rate used by the analyzer.
        capture.center_freq_hz: RF center frequency used in the experiment.
        context.tx: original TxWaveform generated by your TX.
        context.run_dir: folder where you can write artifacts.
        params: the dictionary under rx.params in the YAML config.

    Output:
        RxResult(metrics={...}, artifacts={...})
    """

    metrics = {
        "num_captured_samples": len(capture.samples),
        "sample_rate_hz": capture.sample_rate_hz,
    }
    return RxResult(metrics=metrics)
